
import nltk
from nltk.tokenize import word_tokenize

# Tải dữ liệu cần thiết
nltk.download('punkt')

# Từ điển chứa các từ thông dụng và từ mạnh hơn
strong_words_dict = {
     "essential": "crucial",
    "face": "confront",
    "navigate": "traverse",
    "foster": "cultivate",
    "opportunities": "prospects",
    "success": "achievement",
    "resilient": "tenacious",
    "adaptable": "flexible",
    "enable": "empower",
    "complexities": "intricacies",
    "growth": "progress",
    "development": "advancement",
    "individuals": "people",
    "numerous": "multiple",
    "good": "excellent",
    "bad": "atrocious",
    "happy": "elated",
    "sad": "miserable",
    "big": "enormous",
    "small": "tiny",
    "important": "crucial",
    "love": "cherish",
    "say": "articulate",
    "think": "contemplate",
    "help": "assist",
    "make": "create",
    "get": "obtain",
    "use": "utilize",
    "show": "demonstrate",
    "manage": "oversee",
    "improve": "enhance",
    "build": "construct",
    "understand": "comprehend",
    "achieve": "accomplish",
    "want": "desire",
    "need": "require",
    "work": "collaborate",
    "try": "attempt",
    "start": "initiate",
    "finish": "complete",
    "strong": "robust",
    "fast": "quick",
    "smart": "intelligent",
    "easy": "straightforward",
    "difficult": "challenging",
    "friend": "ally",
    "useful": "beneficial",
    "result": "outcome",
    "think": "consider",
    "speak": "communicate",
    "analyze": "evaluate",
    "assist": "support",
    "design": "devise",
    "organize": "coordinate",
    "lead": "guide",
    "collaborate": "cooperate",
    "create": "innovate",
    "succeed": "thrive",
    "impressive": "remarkable",
    "helpful": "instrumental",
    "innovative": "groundbreaking",
    "manage": "supervise",
    "learn": "master",
    "achieve": "attain",
    "solve": "resolve",
    "promote": "advance",
    "research": "investigate",
    "study": "examine",
    "present": "deliver",
    "assist": "facilitate",
    "engage": "involve",
    "develop": "cultivate",
    "implement": "execute",
    "prepare": "equip",
    "encourage": "motivate",
    "influence": "inspire",
    "monitor": "track",
    "evaluate": "assess",
    "contribute": "donate",
    "advise": "counsel",
    "facilitate": "enable",
    "enhance": "amplify",
    "streamline": "simplify",
    "support": "champion",
    "initiate": "launch",
    "analyze": "scrutinize",
    "consolidate": "integrate",
    "expand": "broaden",
    "improve": "refine",
    "upgrade": "enhance",
    "validate": "authenticate",
    "integrate": "incorporate",
    "network": "connect",
    "communicate": "articulate",
    "prioritize": "focus",
    "conduct": "execute",
    "instruct": "teach",
    "recruit": "attract",
    "guide": "steer",
    "collate": "compile",
    "document": "record",
    "illustrate": "depict",
    "strategize": "plan",
    "forecast": "predict",
    "negotiate": "bargain",
    "produce": "generate",
    "calculate": "compute",
    "assemble": "gather",
    "simplify": "clarify",
    "optimize": "enhance",
    "oversee": "manage",
    "strengthen": "fortify",
    "participate": "engage",
    "articulate": "express",
    "delegate": "assign",
    "communicate": "convey",
    "advocate": "promote",
    "motivate": "inspire",
    "cultivate": "nurture",
    "impart": "provide",
    "formulate": "devise",
    "initiate": "commence",
    "navigate": "guide",
    "refine": "improve",
    "support": "back",
    "collaborate": "partner",
    "excavate": "dig",
    "formulate": "create",
    "disseminate": "spread",
    "transform": "alter",
    "critique": "review",
    "illustrate": "show",
    "convene": "gather",
    "adapt": "adjust",
    "reflect": "ponder",
    "delineate": "describe",
    "evoke": "elicit",
    "compile": "collect",
    "coalesce": "merge",
    "intervene": "step in",
    "fortify": "strengthen",
    "surmount": "overcome",
    "orchestrate": "organize",
    "revolutionize": "transform",
    "synthesize": "combine",
    "validate": "confirm",
    "differentiate": "distinguish",
    "perceive": "discern",
    "propose": "suggest",
    "cultivate": "develop"
}

def replace_with_stronger_words(sentence):
    # Tách câu thành các từ
    words = word_tokenize(sentence)
    
    # Thay thế từ thông dụng bằng từ mạnh hơn
    improved_words = [strong_words_dict.get(word.lower(), word) for word in words]
    
    # Ghép lại các từ thành câu
    improved_sentence = ' '.join(improved_words)
    
    return improved_sentence

